"""Upload everything accumulated locally by bake_local.py into a release.

Run AFTER the GitHub account is reinstated.

Steps:
  1. Read every <tile_id>__city.glb in --out-root.
  2. Create a fresh release tag (or reuse --release-tag if specified).
  3. Upload assets in batches of --chunk-size (the 1000-asset-per-release
     cap forces sharding: if we have >1000 GLBs, we split across multiple
     releases automatically, suffixed -shard-N).
  4. Trigger the manifest rebuild via a workflow_dispatch (or print the
     command for manual run if the workflow trigger isn't possible).

Dry-run by default — pass --apply to actually create/upload.

Usage:
  # Preview what would happen
  python3 src/sync_local_to_release.py --out-root ./local-bake-output

  # Actually upload, using a fresh tag
  python3 src/sync_local_to_release.py --out-root ./local-bake-output --apply

  # Upload to a specific tag (e.g. continuing a partial upload)
  python3 src/sync_local_to_release.py --out-root ./local-bake-output --apply \
      --release-tag bake-2026-05-26-local
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path


# Hard cap on assets per GitHub release. Each tile uses 1 asset (GLB
# only, after the UPLOAD_STL=False policy change). Leave a small buffer
# in case we want to add a per-release manifest stub later.
ASSETS_PER_RELEASE_CAP = 950


def _run_gh(args: list[str], check: bool = True) -> tuple[int, str, str]:
    r = subprocess.run(["gh", *args], capture_output=True, text=True)
    if check and r.returncode != 0:
        raise RuntimeError(
            f"gh {' '.join(args[:3])}… failed (exit {r.returncode}): "
            f"{r.stderr[:400]}"
        )
    return r.returncode, r.stdout, r.stderr


def _create_release(tag: str, title: str, notes: str, apply: bool) -> None:
    print(f"  → create release {tag!r}")
    if not apply:
        return
    _run_gh(["release", "create", tag, "--title", title, "--notes", notes])


def _upload_batch(tag: str, files: list[Path], apply: bool) -> None:
    print(f"  → upload {len(files)} assets to {tag!r}")
    if not apply:
        return
    # gh release upload accepts multiple positional file args. Use
    # --clobber so a re-run after a partial failure replaces partial
    # assets cleanly.
    _run_gh(["release", "upload", tag, "--clobber",
             *[str(f) for f in files]])


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out-root", default="./local-bake-output")
    p.add_argument("--release-tag", default="",
                   help="Existing tag to append to. Empty = create a fresh "
                        "'bake-<date>-local-<N>' tag (or shard tags).")
    p.add_argument("--chunk-size", type=int, default=25,
                   help="Assets per `gh release upload` call. Smaller = more "
                        "robust to network blips (each call is one transaction).")
    p.add_argument("--apply", action="store_true",
                   help="Without this, the script only prints what would happen.")
    args = p.parse_args()

    out_root = Path(args.out_root)
    glbs = sorted(out_root.glob("*__city.glb"))
    if not glbs:
        print(f"[sync] no GLBs under {out_root}", file=sys.stderr)
        return 0
    print(f"[sync] found {len(glbs)} GLBs in {out_root}")
    total_mb = sum(g.stat().st_size for g in glbs) / 1e6
    print(f"[sync] total bytes: {total_mb:.1f} MB")

    # Decide release strategy. Single release if we fit, else shard.
    base_tag = args.release_tag or f"bake-{time.strftime('%Y-%m-%d')}-local"
    n_shards = (len(glbs) + ASSETS_PER_RELEASE_CAP - 1) // ASSETS_PER_RELEASE_CAP
    if n_shards == 1:
        shard_tags = [base_tag]
    else:
        shard_tags = [f"{base_tag}-shard-{i+1}" for i in range(n_shards)]
    print(f"[sync] will use {n_shards} release(s): {shard_tags}")

    if not args.apply:
        print("[sync] dry-run — re-run with --apply to actually push.")
        return 0

    # Try the account check before doing anything destructive. `gh api user`
    # returns the auth'd user; fails fast if the account is still suspended.
    try:
        rc, out, err = _run_gh(["api", "user"], check=False)
        if rc != 0 or "Your account is suspended" in (out + err):
            print(f"[sync] ABORT: account check failed.\n  {err[:400]}",
                  file=sys.stderr)
            return 1
    except RuntimeError as exc:
        print(f"[sync] ABORT: gh api user errored: {exc}", file=sys.stderr)
        return 1

    cursor = 0
    notes_template = (
        "Auto-generated by sync_local_to_release.py — uploads from "
        "local-bake-output. Each asset is a GLB baked by bake_local.py."
    )
    for shard_idx, tag in enumerate(shard_tags):
        shard_glbs = glbs[cursor : cursor + ASSETS_PER_RELEASE_CAP]
        cursor += len(shard_glbs)
        title = f"Local bake {time.strftime('%Y-%m-%d')} (shard {shard_idx+1}/{n_shards})"
        print(f"\n[sync] === shard {shard_idx+1}/{n_shards}: {tag} "
              f"({len(shard_glbs)} GLBs) ===")
        try:
            _create_release(tag, title, notes_template, apply=True)
        except RuntimeError as exc:
            # If the release already exists, that's OK — we'll just upload.
            if "already exists" in str(exc):
                print(f"  (release {tag} already exists, appending)")
            else:
                print(f"[sync] ABORT shard {tag}: {exc}", file=sys.stderr)
                return 1

        # Upload in chunks for robustness.
        for i in range(0, len(shard_glbs), args.chunk_size):
            chunk = shard_glbs[i : i + args.chunk_size]
            try:
                _upload_batch(tag, chunk, apply=True)
                print(f"    {min(i + args.chunk_size, len(shard_glbs))}"
                      f"/{len(shard_glbs)} uploaded")
            except RuntimeError as exc:
                print(f"  ! chunk failed ({exc}); continuing", file=sys.stderr)

    print()
    print("[sync] DONE. Next: rebuild the unified manifest by triggering the "
          "workflow's manifest job, or running build_manifest.py locally and "
          "uploading manifest.json to the newest release.")
    print(f"[sync] Example: gh workflow run bake-all.yml -f limit=1 "
          f"-f admin1_filter=ZZ-noop   # smallest possible to fire manifest")
    return 0


if __name__ == "__main__":
    sys.exit(main())
